[package]
name = "otter"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
subprocess = "0.2"
thiserror = "1"
walkdir = "2"